name: Deploy to GitHub pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: src

    - name: Build website with Hugo
      uses: srt32/hugo-action@v0.0.3
      with:
        args: --source $GITHUB_WORKSPACE/src --destination $GITHUB_WORKSPACE/out --environment production

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: blog
        path: ${{ github.workspace }}/out/
